---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.scr.name }}-svc
  name: {{ .Values.scr.name }}-svc
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Values.scr.name }}
  type: ClusterIP
