---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
  name: {{ .Values.scr.name }}-svc
  namespace: {{ .Values.namespace.name }}
spec:
  ingressClassName: nginx
  rules:
  - host: 'snlavlcde.sas.com'
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.scr.name }}-svc
            port:
              number: 80
        path: /{{ .Values.scr.name }}
        pathType: Prefix